name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test
      - name: SonarCloud Analysis
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Koyeb
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Koyeb Deploy
        run: |
          curl -X POST https://app.koyeb.com/v1/services/242b82d3-acb3-46b4-93f5-e3e1c9f71437/deploy \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"
